services:
  server:
    build: ./TrisServer
    container_name: tris_server
    ports:
      - "5001:5001"

  client:
    build: ./TrisClient
    container_name: tris_client
    depends_on:
      - server
