version: "3.8"

services:
  server:
    build:
      context: ./server  # Costruisce l'immagine del server partendo dal Dockerfile
    ports:
      - "8080:8080"  # Espone la porta 8080
    networks:
      - tris_network  # Collegato alla rete condivisa
    depends_on:
      - db 

  client:
      build:
        context: ./client  # Costruisce l'immagine del client partendo dal Dockerfile
      networks:
        - tris_network  # Collegato alla rete condivisa
      depends_on:
        - server  # Dipende dal servizio server

  db:
      image: postgres:13  # Usa l'immagine di postgres 13
      environment:
        POSTGRES_USER: postgres  # Imposta l'utente postgres
        POSTGRES_PASSWORD: password  # Imposta la password
        POSTGRES_DB: tris_db  # Imposta il nome del database
      ports:
        - "5432:5432"  # Espone la porta 5432 (porta di default di PostgreSQL)
      networks:
        - tris_network  # Collegato alla rete condivisa


  networks:
      tris_network:  # Collegato alla rete condivisa
        driver: bridge  # Usa il driver di rete bridge

  volumes:
    db_data:  # Crea un volume per i dati del database
      driver: local  # Usa il driver di volume locale